version: '3.8'

networks:
  pulso-vivo-network:
    driver: bridge

services:
  # ==========================================
  # MICROSERVICIOS SPRING BOOT
  # ==========================================

  pulso-vivo-kafka-productor-ventas:
    build: ./pulso-vivo-kafka-productor-ventas
    container_name: pulso-vivo-kafka-productor-ventas
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - oracle-xe
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ORACLE_DB_URL=jdbc:oracle:thin:@oracle-xe:1521:XE
      - ORACLE_DB_USERNAME=pulso_vivo
      - ORACLE_DB_PASSWORD=pulso123
    networks:
      - pulso-vivo-network
    restart: unless-stopped

  pulso-vivo-inventory-service:
    build: ./pulso-vivo-inventory-service
    container_name: pulso-vivo-inventory-service
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - oracle-xe
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ORACLE_DB_URL=jdbc:oracle:thin:@oracle-xe:1521:XE
      - ORACLE_DB_USERNAME=pulso_vivo
      - ORACLE_DB_PASSWORD=pulso123
    networks:
      - pulso-vivo-network
    restart: unless-stopped

  pulso-vivo-promotions-service:
    build: ./pulso-vivo-promotions-service
    container_name: pulso-vivo-promotions-service
    ports:
      - "8085:8085"
    depends_on:
      - kafka
      - oracle-xe
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ORACLE_DB_URL=jdbc:oracle:thin:@oracle-xe:1521:XE
      - ORACLE_DB_USERNAME=pulso_vivo
      - ORACLE_DB_PASSWORD=pulso123
    networks:
      - pulso-vivo-network
    restart: unless-stopped

  pulso-vivo-kafka-consumidor-ventas-productor-stock:
    build: ./pulso-vivo-kafka-consumidor-ventas-productor-stock
    container_name: pulso-vivo-kafka-consumidor-ventas-productor-stock
    ports:
      - "8084:8084"
    depends_on:
      - kafka
      - oracle-xe
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ORACLE_DB_URL=jdbc:oracle:thin:@oracle-xe:1521:XE
      - ORACLE_DB_USERNAME=pulso_vivo
      - ORACLE_DB_PASSWORD=pulso123
    networks:
      - pulso-vivo-network
    restart: unless-stopped

  pulso-vivo-sales-consumer:
    build: ./pulso-vivo-sales-consumer
    container_name: pulso-vivo-sales-consumer
    depends_on:
      - kafka
      - oracle-xe
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ORACLE_DB_URL=jdbc:oracle:thin:@oracle-xe:1521:XE
      - ORACLE_DB_USERNAME=pulso_vivo
      - ORACLE_DB_PASSWORD=pulso123
    networks:
      - pulso-vivo-network
    restart: unless-stopped

  pulso-vivo-price-consumer:
    build: ./pulso-vivo-price-consumer
    container_name: pulso-vivo-price-consumer
    depends_on:
      - kafka
      - oracle-xe
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ORACLE_DB_URL=jdbc:oracle:thin:@oracle-xe:1521:XE
      - ORACLE_DB_USERNAME=pulso_vivo
      - ORACLE_DB_PASSWORD=pulso123
    networks:
      - pulso-vivo-network
    restart: unless-stopped

  pulso-vivo-price-monitor:
    build: ./pulso-vivo-price-monitor
    container_name: pulso-vivo-price-monitor
    depends_on:
      - rabbitmq
      - oracle-xe
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin123
      - ORACLE_DB_URL=jdbc:oracle:thin:@oracle-xe:1521:XE
      - ORACLE_DB_USERNAME=pulso_vivo
      - ORACLE_DB_PASSWORD=pulso123
    networks:
      - pulso-vivo-network
    restart: unless-stopped

  pulso-vivo-sales-monitor:
    build: ./pulso-vivo-sales-monitor
    container_name: pulso-vivo-sales-monitor
    depends_on:
      - rabbitmq
      - oracle-xe
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin123
      - ORACLE_DB_URL=jdbc:oracle:thin:@oracle-xe:1521:XE
      - ORACLE_DB_USERNAME=pulso_vivo
      - ORACLE_DB_PASSWORD=pulso123
    networks:
      - pulso-vivo-network
    restart: unless-stopped

  # ==========================================
  # FRONTEND ANGULAR
  # ==========================================

  pulso-vivo-ng:
    build: ./pulso-vivo-ng
    container_name: pulso-vivo-ng
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
      - API_GATEWAY_URL=https://your-api-gateway-url.execute-api.us-east-1.amazonaws.com/prod
      - AZURE_B2C_CLIENT_ID=7549ac9c-9294-4bb3-98d6-752d12b13d81
      - AZURE_B2C_TENANT_ID=82c6cf20-e689-4aa9-bedf-7acaf7c4ead7
      - AZURE_B2C_POLICY=b2c_1_pulso_vivo_register_and_login
    networks:
      - pulso-vivo-network
    restart: unless-stopped

  # ==========================================
  # KAFKA CLUSTER
  # ==========================================

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - pulso-vivo-network
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - pulso-vivo-network
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8089:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - pulso-vivo-network
    restart: unless-stopped

  # ==========================================
  # RABBITMQ
  # ==========================================

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    networks:
      - pulso-vivo-network
    restart: unless-stopped

  # ==========================================
  # ORACLE DATABASE
  # ==========================================

  oracle-xe:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: oracle123
      ORACLE_DATABASE: XE
      ORACLE_USER: pulso_vivo
      ORACLE_PASSWORD_USER: pulso123
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - pulso-vivo-network
    restart: unless-stopped

  # ==========================================
  # MONITORING Y OBSERVABILITY
  # ==========================================

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - pulso-vivo-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - pulso-vivo-network
    restart: unless-stopped

  # ==========================================
  # REVERSE PROXY NGINX (Para desarrollo local)
  # ==========================================

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - pulso-vivo-ng
      - pulso-vivo-kafka-productor-ventas
      - pulso-vivo-inventory-service
      - pulso-vivo-promotions-service
      - pulso-vivo-kafka-consumidor-ventas-productor-stock
    networks:
      - pulso-vivo-network
    restart: unless-stopped

volumes:
  oracle-data:
  grafana-data:
