#!/bin/bash

# 🚀 Información del repositorio Pulso Vivo
echo "==============================================="
echo "🚀 PULSO VIVO - SISTEMA KAFKA DISTRIBUIDO"
echo "==============================================="
echo ""
echo "📋 INFORMACIÓN DEL REPOSITORIO"
echo "-------------------------------"
echo "🔗 GitHub: https://github.com/DiegoBarrosA/pulso-vivo"
echo "👨‍💻 Autor: Diego Barros A."
echo "📅 Fecha: $(date '+%Y-%m-%d %H:%M:%S')"
echo ""
echo "🎯 SISTEMA DESPLEGADO Y FUNCIONAL"
echo "--------------------------------"
echo "✅ Cluster Kafka con 3 brokers"
echo "✅ Ensemble Zookeeper con 3 nodos"
echo "✅ Kafka UI disponible en: http://localhost:8095"
echo "✅ 4 microservicios Spring Boot operativos"
echo "✅ RabbitMQ Management: http://localhost:15672"
echo "✅ Integración con Oracle Database"
echo "✅ Docker Compose orquestando todos los servicios"
echo ""
echo "🔧 COMANDOS ÚTILES"
echo "-------------------"
echo "• Iniciar sistema: docker-compose up --build"
echo "• Validar sistema: ./final-validation.sh"
echo "• Pruebas rápidas: ./simple-test.sh"
echo "• Ver logs: docker-compose logs -f [servicio]"
echo "• Detener sistema: docker-compose down"
echo ""
echo "📚 DOCUMENTACIÓN"
echo "---------------"
echo "• README completo: README.md"
echo "• API Collection: pulso-vivo-api-spec/"
echo "• Scripts de testing: *.sh"
echo ""
echo "🌟 ¡El sistema está publicado en GitHub y listo para usar!"
echo "==============================================="
